services:
  # Web Service (Main Application)
  - type: web
    name: text4quiz
    runtime: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: text4quiz-db
          property: connectionString
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /api/health

# Database (PostgreSQL)
databases:
  - name: text4quiz-db
    databaseName: text4quiz
    user: text4quiz_user